title: Justin Duckett
logo: assets/headshot circle.jpg
description_line1: Digital Analytics Lead | Building Dashboards and Data Pipelines | Python, SQL, BigQuery, dbt | Government of Ontario
# description_line2: Product & Marketing Insights | Data Engineering
#show_downloads: true
theme: jekyll-theme-minimal
