title: Justin Duckett
logo: assets/headshot circle.jpg
description_line1: Digital Analytics Lead at Government of Ontario
# description_line2: Digital Analytics Lead at Government of Ontario | Product & Marketing Insights | Data Engineering
#show_downloads: true
theme: jekyll-theme-minimal
